# 由wallust自动生成，请勿手动修改
# 背景/前景色，和壁纸完全匹配
background #020508
foreground #FFAF5A
selection_background #7D5170
selection_foreground #020508
cursor #F7C89E
cursor_text_color #FFAF5A

# 标准16色终端配色，fastfetch自动继承这些颜色
color0 #03060A
color8 #CA630D

#: black
color1 #280503
color9 #360704

#: red
color2 #3D4C7D
color10 #5165A7

#: green
color3 #656767
color11 #878989

#: yellow
color4 #633628
color12 #844836

#: blue
color5 #7D5170
color13 #A66C95

#: magenta
color6 #B25E20
color14 #ED7D2B

#: cyan
color7 #FFA34F
color15 #F7C89E
