# 由wallust自动生成，请勿手动修改
# 背景/前景色，和壁纸完全匹配
background #03040A
foreground #B4D0FF
selection_background #715B4A
selection_foreground #03040A
cursor #CAD8F4
cursor_text_color #B4D0FF

# 标准16色终端配色，fastfetch自动继承这些颜色
color0 #04060C
color8 #6680B4

#: black
color1 #212C4B
color9 #2C3B64

#: red
color2 #443534
color10 #5A4645

#: green
color3 #3E4745
color11 #525F5C

#: yellow
color4 #4B5068
color12 #646B8B

#: blue
color5 #715B4A
color13 #977963

#: magenta
color6 #78607F
color14 #A080AA

#: cyan
color7 #A6C2FA
color15 #CAD8F4
