# hyprland
$active_border = rgba({{color3 | strip}}aa) rgba({{color6 | strip}}aa) 45deg
$inactive_border = rgba({{background | lighten(0.4) | strip}}aa)
$shadow = rgba(1a1a1aee)
$hyprtasking_bg_color = 0x{{foreground | strip}}aa

# hyprlock
$outer_color = rgba({{color1 | strip}}ee) rgba({{color4 | strip}}ee) 45deg
$check_color = rgba({{color4 | strip}}ee) rgba({{color6 | strip}}ee) 120deg
$fail_color = rgba({{color6 | strip}}ee) rgba({{color7 | strip}}ee) 40deg
