# hyprland
$active_border = rgba(3E4745aa) rgba(78607Faa) 45deg
$inactive_border = rgba(68686Caa)
$shadow = rgba(1a1a1aee)
$hyprtasking_bg_color = 0xB4D0FFaa

# hyprlock
$outer_color = rgba(212C4Bee) rgba(4B5068ee) 45deg
$check_color = rgba(4B5068ee) rgba(78607Fee) 120deg
$fail_color = rgba(78607Fee) rgba(A6C2FAee) 40deg
