# hyprland
$active_border = rgba(656767aa) rgba(B25E20aa) 45deg
$inactive_border = rgba(67696Baa)
$shadow = rgba(1a1a1aee)
$hyprtasking_bg_color = 0xFFAF5Aaa

# hyprlock
$outer_color = rgba(280503ee) rgba(633628ee) 45deg
$check_color = rgba(633628ee) rgba(B25E20ee) 120deg
$fail_color = rgba(B25E20ee) rgba(FFA34Fee) 40deg
