# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = waybar & hyprpaper & firefox
exec-once = swww-daemon
exec-once = mako & waybar & copyq
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = blueman-applet & nm-applet
exec-once = hypridle
exec-once = fcitx5
exec-once = notify-send -i "face-smile" "Welcome back my friend!" "Hyprland activated, good luck!"


##############
### THEMES ###
##############

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct


