source = modules/hyprland/general.conf
source = modules/hyprland/envs.conf
source = modules/hyprland/execs.conf
source = modules/hyprland/keybinds.conf
source = modules/hyprland/rules.conf
source = modules/hyprland/plugins.conf
